### ISSUE TITLE
[Question] What flightmaneuver necessary ?

### ISSUE THREAD

**Issue by BRNKR** [dronecrew/ulog_tools#2]
Hey,

nice tool. But how do I use it in the correct way? I fly some seconds some maneuvers in pitch and roll axis and after that i analyse the log with the tool? I did it and got some PIDs which work. My intention is to use it at its optimum ;) 

best regards

**Comment by jgoppert** [comment]
Pseudo-random-binary-sequence, (aka just a bunch of step responses)
